---
- name: Git clone app repo to /home/
  git:
    repo: "https://github.com/Gustavo-SF/Material-Search-Processing.git"
    dest: /home/mota-engil/{{ project_name }}/

- name: Install requirements.txt
  pip:
    requirements: /home/mota-engil/{{ project_name }}/requirements.txt
    virtualenv: /home/mota-engil/{{ project_name }}/venv
    virtualenv_python: python3.6

- name: Send the .env file
  template:
    src: env_template
    dest: /home/mota-engil/{{ project_name }}/.env

- name: Set up cron job
  cron:
    name: "Run material processing"
    minute: "30"
    hour: "3"
    day: "2"
    job: "cd /home/mota-engil/{{ project_name }}; export $(xargs < .env); venv/bin/python main.py"